name: laxmii_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  loading_animation_widget: ^1.3.0
  pinput: ^5.0.0
  intl: ^0.20.1
  flutter_load_kit: ^0.0.2
  flutter_secure_storage: ^9.2.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  equatable: ^2.0.7
  google_sign_in: ^6.2.2
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  smooth_page_indicator: ^1.2.1
  # fl_chart: ^0.70.2
  pdf: ^3.11.3
  cross_file: ^0.3.4+2
  pdf_render: ^1.4.12
  local_auth: ^2.3.0
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.18.4
  webview_flutter_android: ^4.3.4
  cached_network_image: ^3.4.1
  syncfusion_flutter_charts: ^29.1.35
  flutter_animate: ^4.5.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  dotted_border: ^2.1.0
  # google_maps_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.11
  very_good_analysis: ^6.0.0

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/laxmii_image_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/fonts/



  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-Thin.ttf
          weight: 100 # FontWeight.w100 for thin
        - asset: assets/fonts/Kanit-ThinItalic.ttf
          weight: 200 # FontWeight.w200 for extra light
        - asset: assets/fonts/Kanit-Light.ttf
          weight: 300 # FontWeight.w300 for light
        - asset: assets/fonts/Kanit-LightItalic.ttf
          weight: 300 # FontWeight.w300 for light
        - asset: assets/fonts/Kanit-Regular.ttf
          weight: 400 # FontWeight.w400 for regular
        - asset: assets/fonts/Kanit-BoldItalic.ttf
          weight: 600 # FontWeight.w600 for semi-bold
        - asset: assets/fonts/Kanit-Bold.ttf
          weight: 700 # FontWeight.w700 for bold
        - asset: assets/fonts/Kanit-BlackItalic.ttf
          weight: 800 # FontWeight.w800 for extra bold
        - asset: assets/fonts/Kanit-Black.ttf
          weight: 900 # FontWeight.w900 for black
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
