// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-phjqM6sOgvdw1iOvVAM1zX30Gnhl9ps',
    appId: '1:919567326452:web:8f3f756a780e632486d2a1',
    messagingSenderId: '919567326452',
    projectId: 'laxmii-6a27c',
    authDomain: 'laxmii-6a27c.firebaseapp.com',
    storageBucket: 'laxmii-6a27c.firebasestorage.app',
    measurementId: 'G-W3FJR8RGKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvRp7n_BmSKQF7YhZBuA8rRy-PUWZnzeU',
    appId: '1:919567326452:android:b359d00417dc4e1086d2a1',
    messagingSenderId: '919567326452',
    projectId: 'laxmii-6a27c',
    storageBucket: 'laxmii-6a27c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu0FNbZNdhjwPgAn4_BnChrTByYiaroHE',
    appId: '1:919567326452:ios:e5e9bc179cd17e5d86d2a1',
    messagingSenderId: '919567326452',
    projectId: 'laxmii-6a27c',
    storageBucket: 'laxmii-6a27c.firebasestorage.app',
    androidClientId: '919567326452-frs10jd7k5rhgt06rmtockq2cuts4avn.apps.googleusercontent.com',
    iosClientId: '919567326452-biq54gd68dn9vpl7nnf819e9dsbfrjqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.laxmiiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu0FNbZNdhjwPgAn4_BnChrTByYiaroHE',
    appId: '1:919567326452:ios:e5e9bc179cd17e5d86d2a1',
    messagingSenderId: '919567326452',
    projectId: 'laxmii-6a27c',
    storageBucket: 'laxmii-6a27c.firebasestorage.app',
    androidClientId: '919567326452-frs10jd7k5rhgt06rmtockq2cuts4avn.apps.googleusercontent.com',
    iosClientId: '919567326452-biq54gd68dn9vpl7nnf819e9dsbfrjqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.laxmiiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-phjqM6sOgvdw1iOvVAM1zX30Gnhl9ps',
    appId: '1:919567326452:web:5627f97d5ae8b6ec86d2a1',
    messagingSenderId: '919567326452',
    projectId: 'laxmii-6a27c',
    authDomain: 'laxmii-6a27c.firebaseapp.com',
    storageBucket: 'laxmii-6a27c.firebasestorage.app',
    measurementId: 'G-Z372YED6FY',
  );
}
